### PR TITLE
Adding b and centrality to HepMC output, fix beam particle status code

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
Hi @qgp,
While we wait for Korinna to merge this upstream which can still take some months because she is away, I propose that we include it already in our version.

**Comment by qgp** [comment]
Hi @jgrosseo This code is already in `alice/v2.2.0` (by your #1), what was missing is the tag `v2.2.0-alice1` (done now) and the update of `jewel.sh` in alidist. So, this PR can be closed and we can open one in alidist to bump the tag to `v2.2.0-alice1`. Or do I miss something?

**Comment by jgrosseo** [comment]
Thanks you are right. Can you bump alidist then?

**Comment by qgp** [comment]
@jgrosseo alisw/alidist#2139 opened

**Pull request closed without merging**
